name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      release_tag:
        description: vx.y.z
        required: true
        type: string


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 24
          build-tools: '35.0.0'

      - name: Create keystore.properties
        run: |
          set +x
          echo "NEWS_API_KEY=\"${{ secrets.NEWS_API_KEY }}\"" > keystore.properties

      - name: Build APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease

      - name: Set up Keystore
        run: |
          set +x
          mkdir -p $RUNNER_TEMP/keystores
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > $RUNNER_TEMP/keystores/keystore.jks

      - name: Sign APK
        run: |
          set +x
          $ANDROID_HOME/build-tools/35.0.0/apksigner sign \
            --ks $RUNNER_TEMP/keystores/keystore.jks \
            --ks-key-alias ${{ secrets.KEY_ALIAS }} \
            --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
            --key-pass pass:${{ secrets.KEY_PASSWORD }} \
            --out app-release.apk \
            app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Set APK Name
        id: apk-name
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            VERSION=${GITHUB_REF_NAME#v}
          elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION=${{ github.event.inputs.release_tag }}
            VERSION=${VERSION#v}
          fi
          APK_NAME="meekieD_News_${VERSION}.apk"
          echo "apk_name=$APK_NAME" >> $GITHUB_OUTPUT
          mv app-release.apk $APK_NAME

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-artifact
          path: ${{ steps.apk-name.outputs.apk_name }}
          compression-level: 5

  release:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Set APK Name
        id: apk-name
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            VERSION=${GITHUB_REF_NAME#v}
          elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION=${{ github.event.inputs.release_tag }}
            VERSION=${VERSION#v}
          fi
          APK_NAME="meekieD_News_${VERSION}.apk"
          echo "apk_name=$APK_NAME" >> $GITHUB_OUTPUT

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: apk-artifact

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ steps.apk-name.outputs.apk_name }}